name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-test:
    runs-on: ubuntu-latest     
    steps:
    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python3 test.py


  build-and-push-image:
    runs-on: ubuntu-latest
    steps:   
    - name: Docker Build Tag Publish
      uses: bitovi/github-actions-docker-publish@v1.0.7
      with:
        image_tag: $(date +%s)
        org_name: eyal309
        repo_name: flask_test 
        use_latest: true
        docker_username: ${{ secrets.DOCKER_UNAME }}
        docker_password: ${{ secrets.DOCKER_PAS }}

